services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "9000:9000"
      - "9229:9229" # デバッグ用
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    tty: true
